version: 2
jobs:
    build:
        docker:
            - image: ubuntu:18.04
        steps:
            - checkout
            - run:
                name: Install build tools
                command: >
                    apt update && apt install -y build-essential wget software-properties-common python-software-properties libc++-dev &&
                    apt-get update &&
                    apt-get install -y clang-7 lld-7
            - run:
                name: Run unit test
                command: make unittest CXX=clang++-7
