version: 2
jobs:
    build:
        docker:
            - image: ubuntu:16.04
        steps:
            - checkout
            - run:
                name: Install build tools
                command: >
                    apt update && apt install -y build-essential wget software-properties-common python-software-properties &&
                    wget https://apt.llvm.org/llvm-snapshot.gpg.key && 
                    apt-key add llvm-snapshot.gpg.key &&
                    apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" &&
                    apt-get update &&
                    apt-get install -y clang-6.0
            - run:
                name: Run unit test
                command: make unittest CC=clang-6.0
