version: 2
jobs:
    build:
        docker:
            - image: ubuntu:18.04
        steps:
            - checkout
            - run:
                name: Install build tools
                command: >
                    apt update && apt install -y build-essential wget clang-7 lld-7 libc++-7-dev libc++abi-7-dev
            - run:
                name: Run unit test
                command: make unittest CXX=clang++-7
